// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/cephclient/internal/pkg/domain"
	"sync"
)

// ClientMock is a mock implementation of client.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked client.Client
//		mockedClient := &ClientMock{
//			BIListByObjectFunc: func(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.BIList, error) {
//				panic("mock out the BIListByObject method")
//			},
//			BIListByShardFunc: func(ctx context.Context, containerName string, bucketName string, shardID int) (*domain.BIList, error) {
//				panic("mock out the BIListByShard method")
//			},
//			BucketLayoutFunc: func(ctx context.Context, containerName string, bucketName string) (*domain.Layout, error) {
//				panic("mock out the BucketLayout method")
//			},
//			BucketStatsFunc: func(ctx context.Context, containerName string, bucketName string) (*domain.BucketStats, error) {
//				panic("mock out the BucketStats method")
//			},
//			GetDefaultZoneFunc: func(ctx context.Context, containerName string) (*domain.Zone, error) {
//				panic("mock out the GetDefaultZone method")
//			},
//			HasRawObjectFunc: func(ctx context.Context, containerName string, pool string, rawObject string) (bool, error) {
//				panic("mock out the HasRawObject method")
//			},
//			ListBucketIndexByObjectFunc: func(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.EntryGroup, error) {
//				panic("mock out the ListBucketIndexByObject method")
//			},
//			ListBucketsFunc: func(ctx context.Context, containerName string) ([]string, error) {
//				panic("mock out the ListBuckets method")
//			},
//			ListOmapKeysFunc: func(ctx context.Context, containerName string, indexPool string, indexObject *domain.BucketIndexObject) ([]*domain.BIIndex, error) {
//				panic("mock out the ListOmapKeys method")
//			},
//			ObjectShardFunc: func(ctx context.Context, containerName string, objectName string, totalShards int) (*domain.ObjectShard, error) {
//				panic("mock out the ObjectShard method")
//			},
//			RemoveObjectFunc: func(ctx context.Context, containerName string, bucketName string, objectName string, version string) error {
//				panic("mock out the RemoveObject method")
//			},
//			RemoveOmapKeyFunc: func(ctx context.Context, containerName string, indexPool string, indexObject *domain.BucketIndexObject, key string) error {
//				panic("mock out the RemoveOmapKey method")
//			},
//			RemoveRawObjectFunc: func(ctx context.Context, containerName string, pool string, rawObject string) error {
//				panic("mock out the RemoveRawObject method")
//			},
//		}
//
//		// use mockedClient in code that requires client.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// BIListByObjectFunc mocks the BIListByObject method.
	BIListByObjectFunc func(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.BIList, error)

	// BIListByShardFunc mocks the BIListByShard method.
	BIListByShardFunc func(ctx context.Context, containerName string, bucketName string, shardID int) (*domain.BIList, error)

	// BucketLayoutFunc mocks the BucketLayout method.
	BucketLayoutFunc func(ctx context.Context, containerName string, bucketName string) (*domain.Layout, error)

	// BucketStatsFunc mocks the BucketStats method.
	BucketStatsFunc func(ctx context.Context, containerName string, bucketName string) (*domain.BucketStats, error)

	// GetDefaultZoneFunc mocks the GetDefaultZone method.
	GetDefaultZoneFunc func(ctx context.Context, containerName string) (*domain.Zone, error)

	// HasRawObjectFunc mocks the HasRawObject method.
	HasRawObjectFunc func(ctx context.Context, containerName string, pool string, rawObject string) (bool, error)

	// ListBucketIndexByObjectFunc mocks the ListBucketIndexByObject method.
	ListBucketIndexByObjectFunc func(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.EntryGroup, error)

	// ListBucketsFunc mocks the ListBuckets method.
	ListBucketsFunc func(ctx context.Context, containerName string) ([]string, error)

	// ListOmapKeysFunc mocks the ListOmapKeys method.
	ListOmapKeysFunc func(ctx context.Context, containerName string, indexPool string, indexObject *domain.BucketIndexObject) ([]*domain.BIIndex, error)

	// ObjectShardFunc mocks the ObjectShard method.
	ObjectShardFunc func(ctx context.Context, containerName string, objectName string, totalShards int) (*domain.ObjectShard, error)

	// RemoveObjectFunc mocks the RemoveObject method.
	RemoveObjectFunc func(ctx context.Context, containerName string, bucketName string, objectName string, version string) error

	// RemoveOmapKeyFunc mocks the RemoveOmapKey method.
	RemoveOmapKeyFunc func(ctx context.Context, containerName string, indexPool string, indexObject *domain.BucketIndexObject, key string) error

	// RemoveRawObjectFunc mocks the RemoveRawObject method.
	RemoveRawObjectFunc func(ctx context.Context, containerName string, pool string, rawObject string) error

	// calls tracks calls to the methods.
	calls struct {
		// BIListByObject holds details about calls to the BIListByObject method.
		BIListByObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
			// ObjectName is the objectName argument value.
			ObjectName string
			// ShardID is the shardID argument value.
			ShardID int
		}
		// BIListByShard holds details about calls to the BIListByShard method.
		BIListByShard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
			// ShardID is the shardID argument value.
			ShardID int
		}
		// BucketLayout holds details about calls to the BucketLayout method.
		BucketLayout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
		}
		// BucketStats holds details about calls to the BucketStats method.
		BucketStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
		}
		// GetDefaultZone holds details about calls to the GetDefaultZone method.
		GetDefaultZone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
		}
		// HasRawObject holds details about calls to the HasRawObject method.
		HasRawObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// Pool is the pool argument value.
			Pool string
			// RawObject is the rawObject argument value.
			RawObject string
		}
		// ListBucketIndexByObject holds details about calls to the ListBucketIndexByObject method.
		ListBucketIndexByObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
			// ObjectName is the objectName argument value.
			ObjectName string
			// ShardID is the shardID argument value.
			ShardID int
		}
		// ListBuckets holds details about calls to the ListBuckets method.
		ListBuckets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
		}
		// ListOmapKeys holds details about calls to the ListOmapKeys method.
		ListOmapKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// IndexPool is the indexPool argument value.
			IndexPool string
			// IndexObject is the indexObject argument value.
			IndexObject *domain.BucketIndexObject
		}
		// ObjectShard holds details about calls to the ObjectShard method.
		ObjectShard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// ObjectName is the objectName argument value.
			ObjectName string
			// TotalShards is the totalShards argument value.
			TotalShards int
		}
		// RemoveObject holds details about calls to the RemoveObject method.
		RemoveObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
			// ObjectName is the objectName argument value.
			ObjectName string
			// Version is the version argument value.
			Version string
		}
		// RemoveOmapKey holds details about calls to the RemoveOmapKey method.
		RemoveOmapKey []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// IndexPool is the indexPool argument value.
			IndexPool string
			// IndexObject is the indexObject argument value.
			IndexObject *domain.BucketIndexObject
			// Key is the key argument value.
			Key string
		}
		// RemoveRawObject holds details about calls to the RemoveRawObject method.
		RemoveRawObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// Pool is the pool argument value.
			Pool string
			// RawObject is the rawObject argument value.
			RawObject string
		}
	}
	lockBIListByObject          sync.RWMutex
	lockBIListByShard           sync.RWMutex
	lockBucketLayout            sync.RWMutex
	lockBucketStats             sync.RWMutex
	lockGetDefaultZone          sync.RWMutex
	lockHasRawObject            sync.RWMutex
	lockListBucketIndexByObject sync.RWMutex
	lockListBuckets             sync.RWMutex
	lockListOmapKeys            sync.RWMutex
	lockObjectShard             sync.RWMutex
	lockRemoveObject            sync.RWMutex
	lockRemoveOmapKey           sync.RWMutex
	lockRemoveRawObject         sync.RWMutex
}

// BIListByObject calls BIListByObjectFunc.
func (mock *ClientMock) BIListByObject(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.BIList, error) {
	if mock.BIListByObjectFunc == nil {
		panic("ClientMock.BIListByObjectFunc: method is nil but Client.BIListByObject was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		ShardID       int
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
		ObjectName:    objectName,
		ShardID:       shardID,
	}
	mock.lockBIListByObject.Lock()
	mock.calls.BIListByObject = append(mock.calls.BIListByObject, callInfo)
	mock.lockBIListByObject.Unlock()
	return mock.BIListByObjectFunc(ctx, containerName, bucketName, objectName, shardID)
}

// BIListByObjectCalls gets all the calls that were made to BIListByObject.
// Check the length with:
//
//	len(mockedClient.BIListByObjectCalls())
func (mock *ClientMock) BIListByObjectCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
	ObjectName    string
	ShardID       int
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		ShardID       int
	}
	mock.lockBIListByObject.RLock()
	calls = mock.calls.BIListByObject
	mock.lockBIListByObject.RUnlock()
	return calls
}

// BIListByShard calls BIListByShardFunc.
func (mock *ClientMock) BIListByShard(ctx context.Context, containerName string, bucketName string, shardID int) (*domain.BIList, error) {
	if mock.BIListByShardFunc == nil {
		panic("ClientMock.BIListByShardFunc: method is nil but Client.BIListByShard was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ShardID       int
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
		ShardID:       shardID,
	}
	mock.lockBIListByShard.Lock()
	mock.calls.BIListByShard = append(mock.calls.BIListByShard, callInfo)
	mock.lockBIListByShard.Unlock()
	return mock.BIListByShardFunc(ctx, containerName, bucketName, shardID)
}

// BIListByShardCalls gets all the calls that were made to BIListByShard.
// Check the length with:
//
//	len(mockedClient.BIListByShardCalls())
func (mock *ClientMock) BIListByShardCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
	ShardID       int
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ShardID       int
	}
	mock.lockBIListByShard.RLock()
	calls = mock.calls.BIListByShard
	mock.lockBIListByShard.RUnlock()
	return calls
}

// BucketLayout calls BucketLayoutFunc.
func (mock *ClientMock) BucketLayout(ctx context.Context, containerName string, bucketName string) (*domain.Layout, error) {
	if mock.BucketLayoutFunc == nil {
		panic("ClientMock.BucketLayoutFunc: method is nil but Client.BucketLayout was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
	}
	mock.lockBucketLayout.Lock()
	mock.calls.BucketLayout = append(mock.calls.BucketLayout, callInfo)
	mock.lockBucketLayout.Unlock()
	return mock.BucketLayoutFunc(ctx, containerName, bucketName)
}

// BucketLayoutCalls gets all the calls that were made to BucketLayout.
// Check the length with:
//
//	len(mockedClient.BucketLayoutCalls())
func (mock *ClientMock) BucketLayoutCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}
	mock.lockBucketLayout.RLock()
	calls = mock.calls.BucketLayout
	mock.lockBucketLayout.RUnlock()
	return calls
}

// BucketStats calls BucketStatsFunc.
func (mock *ClientMock) BucketStats(ctx context.Context, containerName string, bucketName string) (*domain.BucketStats, error) {
	if mock.BucketStatsFunc == nil {
		panic("ClientMock.BucketStatsFunc: method is nil but Client.BucketStats was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
	}
	mock.lockBucketStats.Lock()
	mock.calls.BucketStats = append(mock.calls.BucketStats, callInfo)
	mock.lockBucketStats.Unlock()
	return mock.BucketStatsFunc(ctx, containerName, bucketName)
}

// BucketStatsCalls gets all the calls that were made to BucketStats.
// Check the length with:
//
//	len(mockedClient.BucketStatsCalls())
func (mock *ClientMock) BucketStatsCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}
	mock.lockBucketStats.RLock()
	calls = mock.calls.BucketStats
	mock.lockBucketStats.RUnlock()
	return calls
}

// GetDefaultZone calls GetDefaultZoneFunc.
func (mock *ClientMock) GetDefaultZone(ctx context.Context, containerName string) (*domain.Zone, error) {
	if mock.GetDefaultZoneFunc == nil {
		panic("ClientMock.GetDefaultZoneFunc: method is nil but Client.GetDefaultZone was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
	}
	mock.lockGetDefaultZone.Lock()
	mock.calls.GetDefaultZone = append(mock.calls.GetDefaultZone, callInfo)
	mock.lockGetDefaultZone.Unlock()
	return mock.GetDefaultZoneFunc(ctx, containerName)
}

// GetDefaultZoneCalls gets all the calls that were made to GetDefaultZone.
// Check the length with:
//
//	len(mockedClient.GetDefaultZoneCalls())
func (mock *ClientMock) GetDefaultZoneCalls() []struct {
	Ctx           context.Context
	ContainerName string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
	}
	mock.lockGetDefaultZone.RLock()
	calls = mock.calls.GetDefaultZone
	mock.lockGetDefaultZone.RUnlock()
	return calls
}

// HasRawObject calls HasRawObjectFunc.
func (mock *ClientMock) HasRawObject(ctx context.Context, containerName string, pool string, rawObject string) (bool, error) {
	if mock.HasRawObjectFunc == nil {
		panic("ClientMock.HasRawObjectFunc: method is nil but Client.HasRawObject was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		Pool          string
		RawObject     string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		Pool:          pool,
		RawObject:     rawObject,
	}
	mock.lockHasRawObject.Lock()
	mock.calls.HasRawObject = append(mock.calls.HasRawObject, callInfo)
	mock.lockHasRawObject.Unlock()
	return mock.HasRawObjectFunc(ctx, containerName, pool, rawObject)
}

// HasRawObjectCalls gets all the calls that were made to HasRawObject.
// Check the length with:
//
//	len(mockedClient.HasRawObjectCalls())
func (mock *ClientMock) HasRawObjectCalls() []struct {
	Ctx           context.Context
	ContainerName string
	Pool          string
	RawObject     string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		Pool          string
		RawObject     string
	}
	mock.lockHasRawObject.RLock()
	calls = mock.calls.HasRawObject
	mock.lockHasRawObject.RUnlock()
	return calls
}

// ListBucketIndexByObject calls ListBucketIndexByObjectFunc.
func (mock *ClientMock) ListBucketIndexByObject(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.EntryGroup, error) {
	if mock.ListBucketIndexByObjectFunc == nil {
		panic("ClientMock.ListBucketIndexByObjectFunc: method is nil but Client.ListBucketIndexByObject was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		ShardID       int
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
		ObjectName:    objectName,
		ShardID:       shardID,
	}
	mock.lockListBucketIndexByObject.Lock()
	mock.calls.ListBucketIndexByObject = append(mock.calls.ListBucketIndexByObject, callInfo)
	mock.lockListBucketIndexByObject.Unlock()
	return mock.ListBucketIndexByObjectFunc(ctx, containerName, bucketName, objectName, shardID)
}

// ListBucketIndexByObjectCalls gets all the calls that were made to ListBucketIndexByObject.
// Check the length with:
//
//	len(mockedClient.ListBucketIndexByObjectCalls())
func (mock *ClientMock) ListBucketIndexByObjectCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
	ObjectName    string
	ShardID       int
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		ShardID       int
	}
	mock.lockListBucketIndexByObject.RLock()
	calls = mock.calls.ListBucketIndexByObject
	mock.lockListBucketIndexByObject.RUnlock()
	return calls
}

// ListBuckets calls ListBucketsFunc.
func (mock *ClientMock) ListBuckets(ctx context.Context, containerName string) ([]string, error) {
	if mock.ListBucketsFunc == nil {
		panic("ClientMock.ListBucketsFunc: method is nil but Client.ListBuckets was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
	}
	mock.lockListBuckets.Lock()
	mock.calls.ListBuckets = append(mock.calls.ListBuckets, callInfo)
	mock.lockListBuckets.Unlock()
	return mock.ListBucketsFunc(ctx, containerName)
}

// ListBucketsCalls gets all the calls that were made to ListBuckets.
// Check the length with:
//
//	len(mockedClient.ListBucketsCalls())
func (mock *ClientMock) ListBucketsCalls() []struct {
	Ctx           context.Context
	ContainerName string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
	}
	mock.lockListBuckets.RLock()
	calls = mock.calls.ListBuckets
	mock.lockListBuckets.RUnlock()
	return calls
}

// ListOmapKeys calls ListOmapKeysFunc.
func (mock *ClientMock) ListOmapKeys(
	ctx context.Context,
	containerName string,
	indexPool string,
	indexObject *domain.BucketIndexObject,
) ([]*domain.BIIndex, error) {
	if mock.ListOmapKeysFunc == nil {
		panic("ClientMock.ListOmapKeysFunc: method is nil but Client.ListOmapKeys was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		IndexPool     string
		IndexObject   *domain.BucketIndexObject
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		IndexPool:     indexPool,
		IndexObject:   indexObject,
	}
	mock.lockListOmapKeys.Lock()
	mock.calls.ListOmapKeys = append(mock.calls.ListOmapKeys, callInfo)
	mock.lockListOmapKeys.Unlock()
	return mock.ListOmapKeysFunc(ctx, containerName, indexPool, indexObject)
}

// ListOmapKeysCalls gets all the calls that were made to ListOmapKeys.
// Check the length with:
//
//	len(mockedClient.ListOmapKeysCalls())
func (mock *ClientMock) ListOmapKeysCalls() []struct {
	Ctx           context.Context
	ContainerName string
	IndexPool     string
	IndexObject   *domain.BucketIndexObject
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		IndexPool     string
		IndexObject   *domain.BucketIndexObject
	}
	mock.lockListOmapKeys.RLock()
	calls = mock.calls.ListOmapKeys
	mock.lockListOmapKeys.RUnlock()
	return calls
}

// ObjectShard calls ObjectShardFunc.
func (mock *ClientMock) ObjectShard(ctx context.Context, containerName string, objectName string, totalShards int) (*domain.ObjectShard, error) {
	if mock.ObjectShardFunc == nil {
		panic("ClientMock.ObjectShardFunc: method is nil but Client.ObjectShard was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		ObjectName    string
		TotalShards   int
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		ObjectName:    objectName,
		TotalShards:   totalShards,
	}
	mock.lockObjectShard.Lock()
	mock.calls.ObjectShard = append(mock.calls.ObjectShard, callInfo)
	mock.lockObjectShard.Unlock()
	return mock.ObjectShardFunc(ctx, containerName, objectName, totalShards)
}

// ObjectShardCalls gets all the calls that were made to ObjectShard.
// Check the length with:
//
//	len(mockedClient.ObjectShardCalls())
func (mock *ClientMock) ObjectShardCalls() []struct {
	Ctx           context.Context
	ContainerName string
	ObjectName    string
	TotalShards   int
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		ObjectName    string
		TotalShards   int
	}
	mock.lockObjectShard.RLock()
	calls = mock.calls.ObjectShard
	mock.lockObjectShard.RUnlock()
	return calls
}

// RemoveObject calls RemoveObjectFunc.
func (mock *ClientMock) RemoveObject(ctx context.Context, containerName string, bucketName string, objectName string, version string) error {
	if mock.RemoveObjectFunc == nil {
		panic("ClientMock.RemoveObjectFunc: method is nil but Client.RemoveObject was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		Version       string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
		ObjectName:    objectName,
		Version:       version,
	}
	mock.lockRemoveObject.Lock()
	mock.calls.RemoveObject = append(mock.calls.RemoveObject, callInfo)
	mock.lockRemoveObject.Unlock()
	return mock.RemoveObjectFunc(ctx, containerName, bucketName, objectName, version)
}

// RemoveObjectCalls gets all the calls that were made to RemoveObject.
// Check the length with:
//
//	len(mockedClient.RemoveObjectCalls())
func (mock *ClientMock) RemoveObjectCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
	ObjectName    string
	Version       string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		Version       string
	}
	mock.lockRemoveObject.RLock()
	calls = mock.calls.RemoveObject
	mock.lockRemoveObject.RUnlock()
	return calls
}

// RemoveOmapKey calls RemoveOmapKeyFunc.
func (mock *ClientMock) RemoveOmapKey(
	ctx context.Context,
	containerName string,
	indexPool string,
	indexObject *domain.BucketIndexObject,
	key string,
) error {
	if mock.RemoveOmapKeyFunc == nil {
		panic("ClientMock.RemoveOmapKeyFunc: method is nil but Client.RemoveOmapKey was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		IndexPool     string
		IndexObject   *domain.BucketIndexObject
		Key           string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		IndexPool:     indexPool,
		IndexObject:   indexObject,
		Key:           key,
	}
	mock.lockRemoveOmapKey.Lock()
	mock.calls.RemoveOmapKey = append(mock.calls.RemoveOmapKey, callInfo)
	mock.lockRemoveOmapKey.Unlock()
	return mock.RemoveOmapKeyFunc(ctx, containerName, indexPool, indexObject, key)
}

// RemoveOmapKeyCalls gets all the calls that were made to RemoveOmapKey.
// Check the length with:
//
//	len(mockedClient.RemoveOmapKeyCalls())
func (mock *ClientMock) RemoveOmapKeyCalls() []struct {
	Ctx           context.Context
	ContainerName string
	IndexPool     string
	IndexObject   *domain.BucketIndexObject
	Key           string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		IndexPool     string
		IndexObject   *domain.BucketIndexObject
		Key           string
	}
	mock.lockRemoveOmapKey.RLock()
	calls = mock.calls.RemoveOmapKey
	mock.lockRemoveOmapKey.RUnlock()
	return calls
}

// RemoveRawObject calls RemoveRawObjectFunc.
func (mock *ClientMock) RemoveRawObject(ctx context.Context, containerName string, pool string, rawObject string) error {
	if mock.RemoveRawObjectFunc == nil {
		panic("ClientMock.RemoveRawObjectFunc: method is nil but Client.RemoveRawObject was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		Pool          string
		RawObject     string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		Pool:          pool,
		RawObject:     rawObject,
	}
	mock.lockRemoveRawObject.Lock()
	mock.calls.RemoveRawObject = append(mock.calls.RemoveRawObject, callInfo)
	mock.lockRemoveRawObject.Unlock()
	return mock.RemoveRawObjectFunc(ctx, containerName, pool, rawObject)
}

// RemoveRawObjectCalls gets all the calls that were made to RemoveRawObject.
// Check the length with:
//
//	len(mockedClient.RemoveRawObjectCalls())
func (mock *ClientMock) RemoveRawObjectCalls() []struct {
	Ctx           context.Context
	ContainerName string
	Pool          string
	RawObject     string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		Pool          string
		RawObject     string
	}
	mock.lockRemoveRawObject.RLock()
	calls = mock.calls.RemoveRawObject
	mock.lockRemoveRawObject.RUnlock()
	return calls
}
