// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package flow_test

import (
	"context"
	"github.com/neatflowcv/cephclient/internal/pkg/domain"
	"sync"
)

// ClientMock is a mock implementation of client.Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked client.Client
//		mockedClient := &ClientMock{
//			BIListByObjectFunc: func(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.BIList, error) {
//				panic("mock out the BIListByObject method")
//			},
//			BIListByShardFunc: func(ctx context.Context, containerName string, bucketName string, shardID int) (*domain.BIList, error) {
//				panic("mock out the BIListByShard method")
//			},
//			BucketLayoutFunc: func(ctx context.Context, containerName string, bucketName string) (*domain.Layout, error) {
//				panic("mock out the BucketLayout method")
//			},
//			BucketStatsFunc: func(ctx context.Context, containerName string, bucketName string) (*domain.BucketStats, error) {
//				panic("mock out the BucketStats method")
//			},
//			ListBucketsFunc: func(ctx context.Context, containerName string) ([]string, error) {
//				panic("mock out the ListBuckets method")
//			},
//			ObjectShardFunc: func(ctx context.Context, containerName string, objectName string, totalShards int) (*domain.ObjectShard, error) {
//				panic("mock out the ObjectShard method")
//			},
//		}
//
//		// use mockedClient in code that requires client.Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// BIListByObjectFunc mocks the BIListByObject method.
	BIListByObjectFunc func(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.BIList, error)

	// BIListByShardFunc mocks the BIListByShard method.
	BIListByShardFunc func(ctx context.Context, containerName string, bucketName string, shardID int) (*domain.BIList, error)

	// BucketLayoutFunc mocks the BucketLayout method.
	BucketLayoutFunc func(ctx context.Context, containerName string, bucketName string) (*domain.Layout, error)

	// BucketStatsFunc mocks the BucketStats method.
	BucketStatsFunc func(ctx context.Context, containerName string, bucketName string) (*domain.BucketStats, error)

	// ListBucketsFunc mocks the ListBuckets method.
	ListBucketsFunc func(ctx context.Context, containerName string) ([]string, error)

	// ObjectShardFunc mocks the ObjectShard method.
	ObjectShardFunc func(ctx context.Context, containerName string, objectName string, totalShards int) (*domain.ObjectShard, error)

	// calls tracks calls to the methods.
	calls struct {
		// BIListByObject holds details about calls to the BIListByObject method.
		BIListByObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
			// ObjectName is the objectName argument value.
			ObjectName string
			// ShardID is the shardID argument value.
			ShardID int
		}
		// BIListByShard holds details about calls to the BIListByShard method.
		BIListByShard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
			// ShardID is the shardID argument value.
			ShardID int
		}
		// BucketLayout holds details about calls to the BucketLayout method.
		BucketLayout []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
		}
		// BucketStats holds details about calls to the BucketStats method.
		BucketStats []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// BucketName is the bucketName argument value.
			BucketName string
		}
		// ListBuckets holds details about calls to the ListBuckets method.
		ListBuckets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
		}
		// ObjectShard holds details about calls to the ObjectShard method.
		ObjectShard []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ContainerName is the containerName argument value.
			ContainerName string
			// ObjectName is the objectName argument value.
			ObjectName string
			// TotalShards is the totalShards argument value.
			TotalShards int
		}
	}
	lockBIListByObject sync.RWMutex
	lockBIListByShard  sync.RWMutex
	lockBucketLayout   sync.RWMutex
	lockBucketStats    sync.RWMutex
	lockListBuckets    sync.RWMutex
	lockObjectShard    sync.RWMutex
}

// BIListByObject calls BIListByObjectFunc.
func (mock *ClientMock) BIListByObject(ctx context.Context, containerName string, bucketName string, objectName string, shardID int) (*domain.BIList, error) {
	if mock.BIListByObjectFunc == nil {
		panic("ClientMock.BIListByObjectFunc: method is nil but Client.BIListByObject was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		ShardID       int
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
		ObjectName:    objectName,
		ShardID:       shardID,
	}
	mock.lockBIListByObject.Lock()
	mock.calls.BIListByObject = append(mock.calls.BIListByObject, callInfo)
	mock.lockBIListByObject.Unlock()
	return mock.BIListByObjectFunc(ctx, containerName, bucketName, objectName, shardID)
}

// BIListByObjectCalls gets all the calls that were made to BIListByObject.
// Check the length with:
//
//	len(mockedClient.BIListByObjectCalls())
func (mock *ClientMock) BIListByObjectCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
	ObjectName    string
	ShardID       int
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ObjectName    string
		ShardID       int
	}
	mock.lockBIListByObject.RLock()
	calls = mock.calls.BIListByObject
	mock.lockBIListByObject.RUnlock()
	return calls
}

// BIListByShard calls BIListByShardFunc.
func (mock *ClientMock) BIListByShard(ctx context.Context, containerName string, bucketName string, shardID int) (*domain.BIList, error) {
	if mock.BIListByShardFunc == nil {
		panic("ClientMock.BIListByShardFunc: method is nil but Client.BIListByShard was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ShardID       int
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
		ShardID:       shardID,
	}
	mock.lockBIListByShard.Lock()
	mock.calls.BIListByShard = append(mock.calls.BIListByShard, callInfo)
	mock.lockBIListByShard.Unlock()
	return mock.BIListByShardFunc(ctx, containerName, bucketName, shardID)
}

// BIListByShardCalls gets all the calls that were made to BIListByShard.
// Check the length with:
//
//	len(mockedClient.BIListByShardCalls())
func (mock *ClientMock) BIListByShardCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
	ShardID       int
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
		ShardID       int
	}
	mock.lockBIListByShard.RLock()
	calls = mock.calls.BIListByShard
	mock.lockBIListByShard.RUnlock()
	return calls
}

// BucketLayout calls BucketLayoutFunc.
func (mock *ClientMock) BucketLayout(ctx context.Context, containerName string, bucketName string) (*domain.Layout, error) {
	if mock.BucketLayoutFunc == nil {
		panic("ClientMock.BucketLayoutFunc: method is nil but Client.BucketLayout was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
	}
	mock.lockBucketLayout.Lock()
	mock.calls.BucketLayout = append(mock.calls.BucketLayout, callInfo)
	mock.lockBucketLayout.Unlock()
	return mock.BucketLayoutFunc(ctx, containerName, bucketName)
}

// BucketLayoutCalls gets all the calls that were made to BucketLayout.
// Check the length with:
//
//	len(mockedClient.BucketLayoutCalls())
func (mock *ClientMock) BucketLayoutCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}
	mock.lockBucketLayout.RLock()
	calls = mock.calls.BucketLayout
	mock.lockBucketLayout.RUnlock()
	return calls
}

// BucketStats calls BucketStatsFunc.
func (mock *ClientMock) BucketStats(ctx context.Context, containerName string, bucketName string) (*domain.BucketStats, error) {
	if mock.BucketStatsFunc == nil {
		panic("ClientMock.BucketStatsFunc: method is nil but Client.BucketStats was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		BucketName:    bucketName,
	}
	mock.lockBucketStats.Lock()
	mock.calls.BucketStats = append(mock.calls.BucketStats, callInfo)
	mock.lockBucketStats.Unlock()
	return mock.BucketStatsFunc(ctx, containerName, bucketName)
}

// BucketStatsCalls gets all the calls that were made to BucketStats.
// Check the length with:
//
//	len(mockedClient.BucketStatsCalls())
func (mock *ClientMock) BucketStatsCalls() []struct {
	Ctx           context.Context
	ContainerName string
	BucketName    string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		BucketName    string
	}
	mock.lockBucketStats.RLock()
	calls = mock.calls.BucketStats
	mock.lockBucketStats.RUnlock()
	return calls
}

// ListBuckets calls ListBucketsFunc.
func (mock *ClientMock) ListBuckets(ctx context.Context, containerName string) ([]string, error) {
	if mock.ListBucketsFunc == nil {
		panic("ClientMock.ListBucketsFunc: method is nil but Client.ListBuckets was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
	}{
		Ctx:           ctx,
		ContainerName: containerName,
	}
	mock.lockListBuckets.Lock()
	mock.calls.ListBuckets = append(mock.calls.ListBuckets, callInfo)
	mock.lockListBuckets.Unlock()
	return mock.ListBucketsFunc(ctx, containerName)
}

// ListBucketsCalls gets all the calls that were made to ListBuckets.
// Check the length with:
//
//	len(mockedClient.ListBucketsCalls())
func (mock *ClientMock) ListBucketsCalls() []struct {
	Ctx           context.Context
	ContainerName string
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
	}
	mock.lockListBuckets.RLock()
	calls = mock.calls.ListBuckets
	mock.lockListBuckets.RUnlock()
	return calls
}

// ObjectShard calls ObjectShardFunc.
func (mock *ClientMock) ObjectShard(ctx context.Context, containerName string, objectName string, totalShards int) (*domain.ObjectShard, error) {
	if mock.ObjectShardFunc == nil {
		panic("ClientMock.ObjectShardFunc: method is nil but Client.ObjectShard was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		ContainerName string
		ObjectName    string
		TotalShards   int
	}{
		Ctx:           ctx,
		ContainerName: containerName,
		ObjectName:    objectName,
		TotalShards:   totalShards,
	}
	mock.lockObjectShard.Lock()
	mock.calls.ObjectShard = append(mock.calls.ObjectShard, callInfo)
	mock.lockObjectShard.Unlock()
	return mock.ObjectShardFunc(ctx, containerName, objectName, totalShards)
}

// ObjectShardCalls gets all the calls that were made to ObjectShard.
// Check the length with:
//
//	len(mockedClient.ObjectShardCalls())
func (mock *ClientMock) ObjectShardCalls() []struct {
	Ctx           context.Context
	ContainerName string
	ObjectName    string
	TotalShards   int
} {
	var calls []struct {
		Ctx           context.Context
		ContainerName string
		ObjectName    string
		TotalShards   int
	}
	mock.lockObjectShard.RLock()
	calls = mock.calls.ObjectShard
	mock.lockObjectShard.RUnlock()
	return calls
}
